name: PostgreSQL
on: [pull_request]
jobs:
  Test-With-PostgreSQL:
    runs-on: ubuntu-latest
    container: ruby:${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        active_record: [6.1.4, 6.0.4, 5.2.6]
        ruby: [2.6, 2.7, '3.0']
        exclude:
          - active_record: 5.2.6
            ruby: '3.0'
    env:
      ACTIVE_RECORD_VERSION: ${{ matrix.active_record }}
      DATABASE_ADAPTER: postgresql
      INSTALL_PG_GEM: true
      RAILS_ENV: test
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Update bundler
        run: gem update bundler # Use the latest bundler
      - name: Bundle dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake test
